<?php
/**
 * @file
 * Contains voya_im_representative_block.moduel.
 */

/**
 * Implements hook_theme().
 */
function voya_im_representative_block_theme() {
  $theme['representative_authenticated_block'] = [
    'template' => 'representative-authenticated-block',
    'variables' => [
      'block_title' => NULL,
      'wholesaler_name' => NULL,
      'wholesaler_title' => NULL,
      'wholesaler_phone' => NULL,
      'wholesaler_email' => NULL
    ],
  ];
  $theme['representative_anonymous_block'] = [
    'template' => 'representative-anonymous-block',
    'variables' => [
      'block_title' => NULL,
      'block_body' => NULL
    ],
  ];

  return $theme;
}
