<?php

/**
 * @file
 * Contains mar30.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mar30_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mar30 module.
    case 'help.page.mar30':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration Demo D8 Acquia India Stufy Group March 30') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail_alter().
 */
function mar30_mail_alter(&$message){
  if($message['key'] == "page_mail"){
    if($message['params']['contact_form']->id == "departmental_contact_form") {
        if ($message['params']['contact_message']->fields['field_department']['x-default']->list[0]->values['value'] == "Sales"){
            $message['to'] ="sales@tanay.co.in";
        }
        if ($message['params']['contact_message']->fields['field_department']['x-default']->list[0]->values['value'] == "Sales"){
            $message['to'] ="support@tanay.co.in";
        }
    }
  }
}