<?php

/**
 * @file
 * Contains mar30.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_help().
 */
function mar30_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mar30 module.
    case 'help.page.mar30':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration Demo D8 Acquia India Stufy Group March 30') . '</p>';
      return $output;

    default:
  }
}

///**
// * Implements hook_mail_alter().
// */
//function mar30_mail_alter(&$message){
//  if($message['key'] == "page_mail"){
//    if($message['params']['contact_form']->id == "departmental_contact_form") {
//        if ($message['params']['contact_message']->fields['field_department']['x-default']->list[0]->values['value'] == "Sales"){
//            $message['to'] ="sales@tanay.co.in";
//        }
//        if ($message['params']['contact_message']->fields['field_department']['x-default']->list[0]->values['value'] == "Sales"){
//            $message['to'] ="support@tanay.co.in";
//        }
//    }
//  }
//}

///**
// * Implements hook_ENTITY_TYPE_insert().
// */
//function mar30_users_user_insert(Drupal\Core\Entity\EntityInterface $entity) {
//  dsm($entity->id());
//  dsm($entity->getEntityTypeId());
//
//}

/**
 * Implements hook_user_login().
 */
function mar30_user_login($account) {

  $userid = $account->id();
  $queue_factory = \Drupal::service('queue');
  $queue = $queue_factory->get('cron_node_publisher');

  $item = new \stdClass();
  $item->nid = $account->id();
  $queue->createItem($item);

}
